spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET_BASE64}
  bootstrap:
    admin:
      enabled: ${BOOTSTRAP_ADMIN_ENABLED}
      email: ${BOOTSTRAP_ADMIN_EMAIL}
      password: ${BOOTSTRAP_ADMIN_PASSWORD}
